# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accretion < Formula
  desc "Navigate internet resources from the command line."
  homepage "https://github.com/dbtedman/accretion"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/dbtedman/accretion/releases/download/0.0.4/accretion_0.0.4_darwin_amd64"
    sha256 "826f38a7232c543d5788214e887e083b5b5736a3488887a890efe4b444edceb3"

    def install
      bin.install "accretion_0.0.4_darwin_amd64" => "accretion"
    end
  end
  on_arm do
    url "https://github.com/dbtedman/accretion/releases/download/0.0.4/accretion_0.0.4_darwin_arm64"
    sha256 "bb12e8670123e972ddb30077b914425604d049fc7481f82a06598b549d1c1de1"

    def install
      bin.install "accretion_0.0.4_darwin_arm64" => "accretion"
    end
  end
end
