# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aquamarine < Formula
  desc "Provide security by proxying requests to legacy applications."
  homepage "https://github.com/dbtedman/stop"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/stop/releases/download/0.1.3/aquamarine_0.1.3_darwin_amd64"
      sha256 "b495a9a237ecd6ba233f761bac8dc9186bc8de283ac485bde9ed1b7dc36b7553"

      def install
        bin.install "aquamarine_0.1.3_darwin_amd64" => "aquamarine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbtedman/stop/releases/download/0.1.3/aquamarine_0.1.3_darwin_arm64"
      sha256 "b5c3dd51f912ed89b1c820610ae6659f3fb8874e38666b97673f326fcd2a1b21"

      def install
        bin.install "aquamarine_0.1.3_darwin_arm64" => "aquamarine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtedman/stop/releases/download/0.1.3/aquamarine_0.1.3_linux_arm64"
      sha256 "6388a5d5c7a4c6e1028eb30ea3cbdd9133578ba79d971d1612028444d6a47bf2"

      def install
        bin.install "aquamarine_0.1.3_linux_arm64" => "aquamarine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/stop/releases/download/0.1.3/aquamarine_0.1.3_linux_amd64"
      sha256 "8cffe3e0bfe133cded7827d43d0a3d5efe6c0df3766e894b2fa53cc1630853b0"

      def install
        bin.install "aquamarine_0.1.3_linux_amd64" => "aquamarine"
      end
    end
  end
end
