# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conveyance < Formula
  desc "Provide security by proxying requests to legacy applications."
  homepage "https://github.com/dbtedman/conveyance"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dbtedman/conveyance/releases/download/0.2.1/conveyance_0.2.1_darwin_arm64"
      sha256 "c2d3782d3cdbfea97fec2ae28e68860a1b7bb046c03b529b9ed386f208c9c5eb"

      def install
        bin.install "conveyance_0.2.1_darwin_arm64" => "conveyance"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/conveyance/releases/download/0.2.1/conveyance_0.2.1_darwin_amd64"
      sha256 "c6637b4fabe8d3338702f494bc46a1c2ac28335ef9628e541ae83b4c718b5b5b"

      def install
        bin.install "conveyance_0.2.1_darwin_amd64" => "conveyance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtedman/conveyance/releases/download/0.2.1/conveyance_0.2.1_linux_arm64"
      sha256 "0ca7f1de00ca72755b9bdd8216067b43ad3efbc579c8b2dd928d745017269fd7"

      def install
        bin.install "conveyance_0.2.1_linux_arm64" => "conveyance"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/conveyance/releases/download/0.2.1/conveyance_0.2.1_linux_amd64"
      sha256 "6ac852178e900f83de090b5ade30e5afcf8772596450d3b977611bb86516ae55"

      def install
        bin.install "conveyance_0.2.1_linux_amd64" => "conveyance"
      end
    end
  end
end
