# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrutinise < Formula
  desc "Tool to scrutinise website development security."
  homepage "https://github.com/dbtedman/scrutinise"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/scrutinise/releases/download/0.0.5/scrutinise_0.0.5_darwin_amd64"
      sha256 "bdbb595124266a6a670852c1b25175d52f48cfc281cd3c8cc5e942fa8afada43"

      def install
        bin.install "scrutinise_0.0.5_darwin_amd64" => "scrutinise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbtedman/scrutinise/releases/download/0.0.5/scrutinise_0.0.5_darwin_arm64"
      sha256 "cfdc131fa3cd071fb17230a14d6a45672c18bda9124ed4dba5d7ddfe2c81e93f"

      def install
        bin.install "scrutinise_0.0.5_darwin_arm64" => "scrutinise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtedman/scrutinise/releases/download/0.0.5/scrutinise_0.0.5_linux_arm64"
      sha256 "4e93f166361bca4e04d7e6bc4f8f3f0941bc66f5e0fce52474886b2881654875"

      def install
        bin.install "scrutinise_0.0.5_linux_arm64" => "scrutinise"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbtedman/scrutinise/releases/download/0.0.5/scrutinise_0.0.5_linux_amd64"
      sha256 "f3531ea3071683d4464ed7d2bd816a24ab663ef2e6dc27bcee13fd64f5918f5f"

      def install
        bin.install "scrutinise_0.0.5_linux_amd64" => "scrutinise"
      end
    end
  end
end
